# Generated by Django 2.1.1 on 2018-09-12 13:38

from django.db import migrations, models
import django.db.models.deletion
import utils.ubiutils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemid', models.AutoField(db_column='itemid', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=50)),
                ('price', models.DecimalField(db_column='price', decimal_places=2, default=0, max_digits=6)),
                ('created_dtm', models.DateTimeField(auto_now_add=True, db_column='created_dtm')),
                ('type', models.CharField(db_column='type', max_length=30)),
                ('is_available', models.BooleanField(db_column='is_available', default=True)),
                ('points', models.IntegerField(db_column='points', default=0)),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionid', models.AutoField(db_column='transactionid', primary_key=True, serialize=False)),
                ('created_dtm', models.DateTimeField(auto_now_add=True, db_column='created_dtm')),
                ('status', models.CharField(db_column='status', max_length=30)),
                ('free_points_used', models.IntegerField(db_column='free_points_used', default=0)),
                ('purchased_points_used', models.IntegerField(db_column='purchased_points_used', default=0)),
                ('itemid', models.ForeignKey(db_column='itemid', on_delete=django.db.models.deletion.CASCADE, to='points.Item')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='userid', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=50)),
                ('free_points', models.IntegerField(db_column='free_points', default=0)),
                ('free_points_eligible_dtm', models.DateTimeField(default=utils.ubiutils.next_eligible_datetime)),
                ('purchased_points', models.IntegerField(db_column='purchased_points', default=0)),
                ('email', models.EmailField(db_column='email', db_index=True, max_length=254)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_dtm', models.DateTimeField(auto_now_add=True, db_column='created_dtm')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='userid',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='points.User'),
        ),
    ]
