CANBEPURCHASED = [
    'PURCHASE_POINTS',
    'PURCHASE_ITEMS'
]

TRANS_SUCCESS_STATUS = 'SUCCESS'

EXCEPTION_STR = {
    'INSUFFICIENTPOINTS': 'Insufficient Points',
    'CANTPURCHASE': 'Selected Item Can Not Be Purchased'
}

ENABLE_FREE_POINT_SYSTEM = True
FREE_POINTS_ELIGIBILITY = 60  # 3 hours in minutes
MAX_FREE_POINTS_ALLOWED = 200
FREE_ITEM_TYPE = 'FREE_POINTS'
FREE_ITEM_POINTS_VALUE = 50

UBI_BASIC_AUTH = {
    'username': 'UBI_BASIC_USER',
    'password': 'UBI_BASIC_AUTH'
}

JWT_EXPIRY_TIME = 60 * 60 * 24  # 24 Hours in seconds
JWT_SECRET = 'N3v3RExp0s^T[-]IsSecret'
JWT_ALGORITHM = 'HS256'